### PR TITLE
use tagList instead of fluidPage

### PR DESCRIPTION
**Pull request by tyluRp**
Hello! So excited to see an #rstats open source project by JNJ, really really cool! I wanted to contribute something super small, just a slight tweak to the user interface that removes some excess padding on the left and right sides of the app. A reproducible example below:

Whats happening:

```r
library(shiny)
library(shinydashboard)

ui <- shinyUI(
  fluidPage( # <-------------- adds extra padding
    dashboardPage(
      dashboardHeader(),
      dashboardSidebar(),
      dashboardBody()
    )
  )
)
server <- function(input, output) {
  
}

shinyApp(ui, server)
```

How to resolve:

```r
library(shiny)
library(shinydashboard)

ui <- shinyUI(
  tagList( # <-------------- here
    dashboardPage(
      dashboardHeader(),
      dashboardSidebar(),
      dashboardBody()
    )
  )
)
server <- function(input, output) {
  
}

shinyApp(ui, server)
```

### CODE REVIEW

**Comment by CCorrado** [comment]
Hey @tyluRp ! We're excited too. I'm still working through a few kinks on the CI/CD scripts, feel free to reopen your PR once you see a green check on the main branch. Thanks!

**Comment by tyluRp** [comment]
Sounds good, thanks!

**Comment by tyluRp** [comment]
@CCorrado Not sure if I have access to reopen an existing PR, but now that the CI/CD stuff is working, this should merge without conflicts! LMK what you think.

**Comment by CCorrado** [comment]
Hey @tyluRp , you'll have to sync your forked version with the latest main branch in order to reopen your PR!

image

**Comment by tyluRp** [comment]
Thanks, I must be rusty because it took me awhile to figure out how to sync my fork 😅

**Pull request closed without merging**
